### PR TITLE
Bump allowed mongoose version

### PR DESCRIPTION
**Pull request by TKDBB84**
we've been using this successfully with latest mongoose, this bumps it to allow any subversion of 5.

### CODE REVIEW

**Comment by michelzanini** [comment]
Can we please merge this?

**Comment by TKDBB84** [comment]
@michelzanini in the meantime we've been using npm8's override feature to get around any errors:
```
  "overrides": {
    "cls-mongoose-shim": {
      "mongoose": "$mongoose"
    }
  }
```

**Comment by michelzanini** [comment]
Maybe add @wayglem as reviewer to see if gets notified?

**Comment by wayglem** [comment]
Hi, 
Sorry I completely missed the previous notifications. I'll test it and merge it ASAP.
Thanks a lot @TKDBB84

**Comment by wayglem** [comment]
Version 0.0.8 is published on npm :confetti_ball: 

Thank you guys for your help!
Cheers

**Pull request merged**
